---
title: "Coding residential income data"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

# Setup

```{r "setup", message=FALSE, warning=FALSE, include=FALSE}
suppressWarnings(library(ggplot2))
suppressWarnings(library(dplyr))
suppressWarnings(library(boot))
suppressWarnings(library(readstata13))
suppressWarnings(library(stargazer))
suppressWarnings(library(lfe))
suppressWarnings(library(knitr))
suppressWarnings(library(geosphere))
suppressWarnings(library(Hmisc))
suppressWarnings(library(pastecs))
suppressWarnings(library(foreign))
suppressWarnings(library(FENmlm))

set.seed(92373247); 
  
rm(list=ls())


## include functions
source(paste0(Sys.getenv("HOME"), "/Rinit/profile.R"))
knitr::opts_knit$set(root.dir = BGDSLKCELLPHONE_DATA) 

source("aux_functions.r")
source("income_coding_functions.r")

```


# Data preparation


```{r, include=FALSE}

    ## Load DHUTS Data
    #- generated in "code/BGD code DHUTS part2.Rmd"
      dhuts <- readRDS("data_coded_bgd/dhuts/coded_dhuts.rds")

    ## BGD data
      # Czone area and distance to the city center
      antenna.BGD <- read.csv(file="data_raw_bgd/other/towers_bgd.csv")
      antenna.BGD <- antenna.BGD %>% 
        rename(lat = latitude, lon = longitude, THAID = thaid) %>% 
        select(tower, czone, lat, lon, THAID, thaname, area_km2) %>% unique()
      stopifnot(antenna.BGD %>% unique_id(tower))
  
      # load commuting data
      commuting.BGD    <- read.dta13(file="data_coded_bgd/flows/daily_trips_odmatrix_gravity.dta")
      commuting.BGD.hw <- read.dta13(file="data_coded_bgd/flows/home_work_odmatrix_gravity.dta")
  
      commuting.BGD    <- commuting.BGD    %>% 
        rename(destination.czone=destination_czone, origin.czone=origin_czone)
      commuting.BGD.hw <- commuting.BGD.hw %>% 
        rename(destination.czone=destination_czone, origin.czone=origin_czone)
      
      # merge tower area and coordinates
      commuting.BGD <- commuting.BGD %>% 
        left_join(antenna.BGD %>% select(tower, lat, lon, area_km2) %>% 
                    rename(origin = tower,      lat_o = lat, lon_o = lon, km2_tower_o = area_km2), by="origin") %>% 
        left_join(antenna.BGD %>% select(tower, lat, lon, area_km2) %>% 
                    rename(destination = tower, lat_d = lat, lon_d = lon, km2_tower_d = area_km2), by="destination")
      
      commuting.BGD.hw <- commuting.BGD.hw %>% 
        left_join(antenna.BGD %>% select(tower, lat, lon, area_km2) %>% 
                    rename(origin = tower,      lat_o = lat, lon_o = lon, km2_tower_o = area_km2), by="origin") %>% 
        left_join(antenna.BGD %>% select(tower, lat, lon, area_km2) %>% 
                    rename(destination = tower, lat_d = lat, lon_d = lon, km2_tower_d = area_km2), by="destination")

      
    ## SLK data
      towers_cordinates.SLK <- read.csv(file="data_raw_slk/other/towers_slk.csv")

      # load commuting data
      commuting.SLK    <- read.dta13(file="data_coded_slk/flows/daily_trips_odmatrix_gravity.dta")
      commuting.SLK.hw <- read.dta13(file="data_coded_slk/flows/home_work_odmatrix_gravity.dta")
  
      # merge tower area and coordinates
      commuting.SLK <- commuting.SLK %>% 
        left_join(towers_cordinates.SLK %>% select(tower, latitude, longitude, area_km2) %>% 
                    rename(origin = tower,      lat_o = latitude, lon_o = longitude, km2_tower_o = area_km2), by="origin") %>% 
        left_join(towers_cordinates.SLK %>% select(tower, latitude, longitude, area_km2) %>% 
                    rename(destination = tower, lat_d = latitude, lon_d = longitude, km2_tower_d = area_km2), by="destination")
      commuting.SLK.hw <- commuting.SLK.hw %>% 
        left_join(towers_cordinates.SLK %>% select(tower, latitude, longitude, area_km2) %>% 
                    rename(origin = tower,      lat_o = latitude, lon_o = longitude, km2_tower_o = area_km2), by="origin") %>% 
        left_join(towers_cordinates.SLK %>% select(tower, latitude, longitude, area_km2) %>% 
                    rename(destination = tower, lat_d = latitude, lon_d = longitude, km2_tower_d = area_km2), by="destination")


      
    ## load gravity equation results                       
      est.gravity.BGD    = read.csv("data_coded/dfe_bgd_daily_trips.csv")
      est.gravity.BGD.hw = read.csv("data_coded/dfe_bgd_home_work.csv")
      
      est.gravity.SLK    = read.csv("data_coded/dfe_slk_daily_trips.csv")
      est.gravity.SLK.hw = read.csv("data_coded/dfe_slk_home_work.csv")
      


## load census PCA data
  census_bgd <- read.dta13(file = 'data_coded_bgd/census/censuspop_tower_allvars.dta')
  census_bgd <- census_bgd %>% select(tower, pca_thana_tower_avg, tot_pop_isx)
  
  census_slk <- read.dta13(file = 'data_coded_slk/census/censuspop_tower_allvars.dta')
  census_slk <- census_slk %>% select(tower, pca1, population)
  
   census_bgd <- census_bgd %>%
      mutate(census_outcomevar = pca_thana_tower_avg)

   census_slk <- census_slk %>%
      mutate(census_outcomevar = pca1)
   
   
## distance to CBD
  dist2cbd_bgd <- read.dta13(file = 'data_coded_bgd/other/dist2cbd.dta')
  census_bgd <- census_bgd %>% left_join(dist2cbd_bgd, by="tower")
  dist2cbd_slk <- read.dta13(file = 'data_coded_slk/other/dist2cbd.dta')
  census_slk <- census_slk %>% left_join(dist2cbd_slk, by="tower")
  
  
## merge coordinates
  census_bgd <- census_bgd %>% left_join(antenna.BGD, by='tower')

  census_slk <- census_slk %>% 
     left_join(rename(towers_cordinates.SLK, lon=longitude, lat=latitude), by='tower')
  

```  


# (2) Baseline income results

- Baseline epsilon: 8.3 (from our workplace income estimation)
- Baseline: use all samples
- Add `unit` and `time` for computing Conley SE later on

```{r}

commuting.BGD    <- commuting.BGD    %>% mutate(sample_income_coding = 1)
commuting.SLK    <- commuting.SLK    %>% mutate(sample_income_coding = 1)
commuting.BGD.hw    <- commuting.BGD.hw    %>% mutate(sample_income_coding = 1)
commuting.SLK.hw    <- commuting.SLK.hw    %>% mutate(sample_income_coding = 1)

census.BGD.income.hw <- residential_income_coding(commuting.BGD.hw, est.gravity.BGD.hw, census_bgd, epsilon=8.3) %>%
                            filter(!is.na(res.meanlogy.v00)) %>% 
                            mutate(unit = 1, time = 1)

census.SLK.income.hw <- residential_income_coding(commuting.SLK.hw, est.gravity.SLK.hw, census_slk, epsilon=8.3) %>% 
                            filter(!is.na(res.meanlogy.v00)) %>% 
                            mutate(unit = 1, time = 1)

```


# (3) Data for robustness

```{r}

commuting.BGD.exclnb <- commuting.BGD.hw %>% mutate(sample_income_coding = sample_v2)
commuting.SLK.exclnb <- commuting.SLK.hw %>% mutate(sample_income_coding = sample_v2)

census.BGD.income.exclnb <- residential_income_coding(commuting.BGD.exclnb, 
                                                     est.gravity.BGD.hw, census_bgd, 
                                                     epsilon=8.3) %>%
                              filter(!is.na(res.meanlogy.v00)) %>% 
                              mutate(unit=1, time=1) 

census.SLK.income.exclnb <- residential_income_coding(commuting.SLK.exclnb, 
                                                     est.gravity.SLK.hw, census_slk, 
                                                     epsilon=8.3) %>% 
                              filter(!is.na(res.meanlogy.v00)) %>% 
                              mutate(unit=1, time=1)

census.BGD.income.daily <- residential_income_coding(commuting.BGD, est.gravity.BGD, census_bgd, epsilon=8.3) %>%
                            filter(!is.na(res.meanlogy.v00)) %>% 
                            mutate(unit=1, time=1)

census.SLK.income.daily <- residential_income_coding(commuting.SLK, est.gravity.SLK, census_slk, epsilon=8.3) %>% 
                            filter(!is.na(res.meanlogy.v00)) %>% 
                            mutate(unit=1, time=1)
```


# (4) Save

```{r}

  save(census.BGD.income.hw, census.BGD.income.exclnb, census.BGD.income.daily,
       census.SLK.income.hw, census.SLK.income.exclnb, census.SLK.income.daily,
       file="data_coded/residential_income.Rdata")
 
```

