---
title: "Comparison with Machine Learning Predictions"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

# Outline

```{r "setup", message=FALSE, warning=FALSE, include=FALSE}
suppressWarnings(library(ggplot2))
suppressWarnings(library(dplyr))
suppressWarnings(library(tidyr))
suppressWarnings(library(boot))
suppressWarnings(library(readstata13))
suppressWarnings(library(stargazer))
suppressWarnings(library(lfe))
suppressWarnings(library(knitr))
suppressWarnings(library(geosphere))
suppressWarnings(library(Hmisc))
suppressWarnings(library(pastecs))
suppressWarnings(library(foreign))
suppressWarnings(library(caTools))
suppressWarnings(library(glmnet))
suppressWarnings(library(glmnetUtils))
suppressWarnings(library(gbm))
suppressWarnings(library(randomForest))

set.seed(92373247); 
  
rm(list=ls())


## include functions
source(paste0(Sys.getenv("HOME"), "/Rinit/profile.R"))
knitr::opts_knit$set(root.dir = BGDSLKCELLPHONE_DATA) 
source("aux_functions.r")
source("income_analysis_ML_functions.r")

```



# 1. Load Data (BGD)

### survey income

```{r, include=TRUE}

    ## Load czone
      czone <- readRDS("data_coded_bgd/dhuts/czone_BGD.rds")

    ## commuting in BGD
      commuting.BGD.hw <- read.dta13(file="data_coded_bgd/flows/home_work_odmatrix_gravity.dta")
      commuting.BGD.hw <- commuting.BGD.hw %>% 
        rename(destination.czone=destination_czone, origin.czone=origin_czone)

    ## dhuts at destination level
      dhuts.y.dest.hw     <- readRDS("data_coded_bgd/workplace_income/dhuts_dest_y_hw.rds")


```    


### nighttime lights and census data

```{r}

  load(file="data_coded/residential_income.Rdata")

  census.BGD.income <- census.BGD.income.hw %>% 
    mutate(
      log_res_density = log(volume.origin/km2_tower_d),
      log_distCBD = log(distCBD),
      const = 1
    )

```



### Covariates for ML

```{r}

covariates_df <- readRDS( "data_coded_bgd/ML/covariates_df_ML.Rds")

```


### merge with survey income etc.

```{r}

  ## merge tower-level information to czone-level data   
    tower.BGD <- read.csv(file="data_raw_bgd/other/towers_bgd.csv")
    tower_czone_df <- tower.BGD %>%
       dplyr::distinct(tower, czone)


    # weight covariates at c-zone level
    commuting.BGD.hw.dest <- commuting.BGD.hw %>% 
      group_by(destination) %>% 
      summarise(volume = sum(volume, na.rm=T)) %>% 
      ungroup() %>% 
      rename(tower = destination)
    
    czone_covariates_df <- merge(tower_czone_df, covariates_df, by="tower") %>%
      left_join(commuting.BGD.hw.dest, by="tower") %>% 
      group_by(czone) %>% #mutate(tower_num = unique(tower)) %>%
      select(-c(tower))%>% 
      mutate(volume = ifelse(!is.na(volume), volume, 0)) %>% 
      dplyr::summarize_all(funs(weighted.mean(., w=volume, na.rm=TRUE))) %>% 
      select(-volume)

    czone_covariates_df <- czone_covariates_df[!is.na(czone_covariates_df$czone), ]

###  with survey income

    dhuts.y.dest.hw <- merge(
      dhuts.y.dest.hw, 
      rename(czone_covariates_df, destination.czone=czone), 
      by="destination.czone"
    )

    ## use cell-phone data weighted dhuts residual income
    dhuts.y.dest.hw.resid <- dhuts.y.dest.hw %>% 
      rename(mean.logy = mean.logy.dhuts.no_weight.r) %>% 
      filter(!is.na(mean.logy.v00.adj.dest) & !is.na(mean.logy))
    
    ## use cell-phone data weighted dhuts income
    dhuts.y.dest.hw <- dhuts.y.dest.hw %>% 
      rename(mean.logy = mean.logy.dhuts.no_weight) %>% 
      filter(!is.na(mean.logy.v00.adj.dest) & !is.na(mean.logy))
    
    ## starting column number for features
    feature_start_col_dhuts <- which(colnames(dhuts.y.dest.hw) == "weekday_0_totfreq") 


###  with residenial income
    # replace tower-level missing feature to zero
    covariates_df_nonmiss <- covariates_df
    covariates_df_nonmiss[is.na(covariates_df_nonmiss)] <- 0
    census.BGD.income <- census.BGD.income %>% left_join(covariates_df_nonmiss, by='tower')
  
    ## starting column number for features
    feature_start_col_viirs <- which(colnames(census.BGD.income) == "weekday_0_totfreq") 


    
```




# 3. report results of ML

## 3.1 survey income

```{r}

## destination level

    # baseline
      survey_income_ML(df = dhuts.y.dest.hw, 
                       outfile = paste0(BGDSLKCELLPHONE_DATA, "tables/table_3/table_3.tex"), 
                       feature_start_col = feature_start_col_dhuts, alpha=0.5, splitratio = 0.5)

    # cross-validation table
      survey_income_ML_CV(df = dhuts.y.dest.hw,
                 outfile = paste0(BGDSLKCELLPHONE_DATA, "tables/table_F1/table_F1.tex"), 
                 feature_start_col = feature_start_col_dhuts, alpha=0.5,  splitratio = 0.5)
    

```

## 3.2 residential income

```{r}

### residential income (census CPA)
    residential_ML(df = filter(census.BGD.income, !is.na(pca_thana_tower_avg)), 
           outfile = paste0(BGDSLKCELLPHONE_DATA, "tables/table_4B/table_4B.tex"), 
           outvar = "pca_thana_tower_avg", alpha=0.5, feature_start_col = feature_start_col_viirs, expost_optimal = T, splitratio = 0.5, debug = T, weight_var="volume.origin")


```


